import { WorkGroup } from '../../lib/types';

export const mockWorkGroup: WorkGroup = {
  name: 'AI Ethics WG',
  type: 'Governance',
  dateOfCreation: '12/03/2023',
  status: 'Active',
  anchorContacts: [
    { name: 'Ana Pérez', role: 'Lead', handle: '@anaperez' },
    { name: 'Luis Gómez', role: 'Coordinator', handle: '@luisg' },
  ],
  missionStatement: 'Promover el desarrollo y la implementación ética de la inteligencia artificial en la gobernanza.',
  goalsAndFocus: ['Education', 'Governance', 'Policy'],
  totalMembers: '8 activos | 3 observadores | 2 pendientes',
  roles: ['Core Contributors', 'Observers', 'Advisors'],
  memberDirectoryLink: '#',
  keyDeliverables: [
    {
      title: 'AI Ethics Guidelines',
      status: 'Completed',
      timeline: 'Q1 2024',
      description: 'Documento con lineamientos éticos para IA en gobernanza.'
    },
    {
      title: 'Ethics Workshop',
      status: 'In Progress',
      timeline: 'Q2 2024',
      description: 'Taller interactivo para miembros y comunidad.'
    }
  ],
  proposalSubmissions: [
    {
      title: 'AI Policy Proposal',
      status: 'Under Review',
      link: '#',
      votingResults: '5 Consent / 1 Object / 2 Abstain'
    }
  ],
  frequency: 'Weekly',
  meetingCalendarLink: '#',
  meetingNotesArchiveLink: '#',
  eventHostingParticipation: ['AI Ethics Webinar', 'Panel en Governance Summit'],
  createReportLink: '#',
  lastReportLink: '#',
  selfEvaluation: '🟢🟡',
  communityFeedback: 'Positivo, sugerencias de mayor apertura.',
  votingMetrics: '80% Participation / 90% Approval / 1 Abstention',
  currentBudgetTier: 'T1',
  currentBudget: '1500 USD',
  utilizationSummary: '70% ejecutado en talleres y materiales.',
  fundingSources: ['Ambassador Program', 'Community Grants'],
  nextProposal: '09/15/2024',
  budgetProposalLink: '#',
  pastBudgets: [
    { title: 'Q2 2024 (Actual)', amount: '1500 USD', link: '#' },
    { title: 'Q1 2024', amount: '1200 USD', link: '#' },
    { title: 'Q4 2023', amount: '1000 USD', link: '#' },
  ],
  collaborations: [
    { groupName: 'Open Data WG', collaborationType: 'Joint Workshop', contact: '@opendata' }
  ],
  toolsUsed: ['GitHub', 'Notion', 'Zoom'],
  relatedProposals: ['#', '#'],
  ongoingDecisions: [
    { title: 'Adopt New Charter', dueDate: '07/30/2024', status: 'Consent' }
  ],
  voteNowLink: '#',
  consensusArchiveLink: '#',
  participationMetrics: '12 Votes | 8 Comments | 85% Engagement',
  nextSteps: ['Finalizar taller de ética', 'Publicar resultados'],
  milestoneTimelineLink: '#',
  openCalls: ['Convocatoria para nuevos miembros'],
  nextCycleProposalIdeas: ['Implementar sistema de mentoría']
};

export const mockWorkGroups = [
  {
    name: 'African Guild',
    type: 'Regional',
    dateOfCreation: '01/02/2023',
    status: 'Active',
    anchorContacts: [{ name: 'Kwame Nkrumah', role: 'Lead', handle: '@kwame' }],
    missionStatement: 'Impulsar la colaboración y el desarrollo en África.',
    goalsAndFocus: ['Inclusión', 'Desarrollo'],
    totalMembers: '10 activos | 2 observadores | 1 pendiente',
    roles: ['Core Contributors', 'Observers'],
    memberDirectoryLink: '#',
    keyDeliverables: [{ title: 'African Summit', status: 'Completed', timeline: 'Q2 2023', description: 'Evento anual de la guild.' }],
    proposalSubmissions: [],
    frequency: 'Monthly',
    meetingCalendarLink: '#',
    meetingNotesArchiveLink: '#',
    eventHostingParticipation: ['African Summit 2023'],
    createReportLink: '#',
    lastReportLink: '#',
    selfEvaluation: '🟢🟡',
    communityFeedback: 'Muy positivo',
    votingMetrics: '90% Participation / 95% Approval / 0 Abstention',
    currentBudgetTier: 'T2',
    currentBudget: '1200 USD',
    utilizationSummary: '80% ejecutado en eventos.',
    fundingSources: ['Regional Grants'],
    nextProposal: '10/01/2024',
    budgetProposalLink: '#',
    pastBudgets: [
      { title: 'Q2 2024 (Actual)', amount: '1200 USD', link: '#' },
      { title: 'Q1 2024', amount: '1000 USD', link: '#' }
    ],
    collaborations: [],
    toolsUsed: ['Discord'],
    relatedProposals: [],
    ongoingDecisions: [],
    voteNowLink: '#',
    consensusArchiveLink: '#',
    participationMetrics: '10 Votes | 5 Comments | 80% Engagement',
    nextSteps: ['Organizar próximo summit'],
    milestoneTimelineLink: '#',
    openCalls: ['Convocatoria para nuevos miembros'],
    nextCycleProposalIdeas: ['Expandir a nuevas regiones']
  },
  {
    name: 'AI Ethics WG',
    type: 'Governance',
    dateOfCreation: '12/03/2023',
    status: 'Active',
    anchorContacts: [{ name: 'Ana Pérez', role: 'Lead', handle: '@anaperez' }],
    missionStatement: 'Promover la ética en IA.',
    goalsAndFocus: ['Ética', 'Gobernanza'],
    totalMembers: '8 activos | 3 observadores | 2 pendientes',
    roles: ['Core Contributors'],
    memberDirectoryLink: '#',
    keyDeliverables: [{ title: 'AI Ethics Guidelines', status: 'Completed', timeline: 'Q1 2024', description: 'Documento de lineamientos.' }],
    proposalSubmissions: [],
    frequency: 'Weekly',
    meetingCalendarLink: '#',
    meetingNotesArchiveLink: '#',
    eventHostingParticipation: ['Webinar Ética IA'],
    createReportLink: '#',
    lastReportLink: '#',
    selfEvaluation: '🟢',
    communityFeedback: 'Positivo',
    votingMetrics: '80% Participation / 90% Approval / 1 Abstention',
    currentBudgetTier: 'T1',
    currentBudget: '1500 USD',
    utilizationSummary: '70% ejecutado en talleres.',
    fundingSources: ['Ambassador Program'],
    nextProposal: '09/15/2024',
    budgetProposalLink: '#',
    pastBudgets: [
      { title: 'Q2 2024 (Actual)', amount: '1500 USD', link: '#' },
      { title: 'Q1 2024', amount: '1200 USD', link: '#' }
    ],
    collaborations: [],
    toolsUsed: ['Notion', 'Zoom'],
    relatedProposals: [],
    ongoingDecisions: [],
    voteNowLink: '#',
    consensusArchiveLink: '#',
    participationMetrics: '12 Votes | 8 Comments | 85% Engagement',
    nextSteps: ['Finalizar taller de ética'],
    milestoneTimelineLink: '#',
    openCalls: ['Convocatoria para nuevos miembros'],
    nextCycleProposalIdeas: ['Implementar sistema de mentoría']
  },
  {
    name: 'AI Sandbox/Think Tank',
    type: 'Research',
    dateOfCreation: '03/04/2023',
    status: 'Pending',
    anchorContacts: [{ name: 'Sofia Lee', role: 'Coordinator', handle: '@sofialee' }],
    missionStatement: 'Explorar nuevas ideas en IA.',
    goalsAndFocus: ['Innovación', 'Experimentación'],
    totalMembers: '4 activos | 1 observador | 0 pendientes',
    roles: ['Investigadores'],
    memberDirectoryLink: '#',
    keyDeliverables: [{ title: 'Sandbox Report', status: 'In Progress', timeline: 'Q3 2024', description: 'Informe de experimentos.' }],
    proposalSubmissions: [],
    frequency: 'Monthly',
    meetingCalendarLink: '#',
    meetingNotesArchiveLink: '#',
    eventHostingParticipation: ['Demo Day'],
    createReportLink: '#',
    lastReportLink: '#',
    selfEvaluation: '🟡',
    communityFeedback: 'En progreso',
    votingMetrics: '60% Participation / 70% Approval / 2 Abstention',
    currentBudgetTier: 'T3',
    currentBudget: '900 USD',
    utilizationSummary: '50% ejecutado en prototipos.',
    fundingSources: ['Research Grants'],
    nextProposal: '11/01/2024',
    budgetProposalLink: '#',
    pastBudgets: [
      { title: 'Q2 2024 (Actual)', amount: '900 USD', link: '#' },
      { title: 'Q1 2024', amount: '700 USD', link: '#' }
    ],
    collaborations: [],
    toolsUsed: ['GitHub'],
    relatedProposals: [],
    ongoingDecisions: [],
    voteNowLink: '#',
    consensusArchiveLink: '#',
    participationMetrics: '4 Votes | 2 Comments | 60% Engagement',
    nextSteps: ['Publicar resultados'],
    milestoneTimelineLink: '#',
    openCalls: ['Convocatoria para ideas'],
    nextCycleProposalIdeas: ['Lanzar hackathon']
  },
  {
    name: 'Open Data WG',
    type: 'Data',
    dateOfCreation: '01/10/2022',
    status: 'Inactive',
    anchorContacts: [
      { name: 'Carlos Ruiz', role: 'Lead', handle: '@carlosr' }
    ],
    missionStatement: 'Fomentar la apertura y el uso ético de datos públicos.',
    goalsAndFocus: ['Open Data', 'Transparency'],
    totalMembers: '5 activos | 2 observadores | 1 pendiente',
    roles: ['Core Contributors', 'Observers'],
    memberDirectoryLink: '#',
    keyDeliverables: [
      { title: 'Open Data Portal', status: 'Completed', timeline: 'Q4 2023', description: 'Portal web para datasets abiertos.' }
    ],
    proposalSubmissions: [],
    frequency: 'Monthly',
    meetingCalendarLink: '#',
    meetingNotesArchiveLink: '#',
    eventHostingParticipation: ['Hackathon de Datos Abiertos'],
    createReportLink: '#',
    lastReportLink: '#',
    selfEvaluation: '🟢🟡',
    communityFeedback: 'Muy positivo',
    votingMetrics: '90% Participation / 95% Approval / 0 Abstention',
    currentBudgetTier: 'T2',
    currentBudget: '800 USD',
    utilizationSummary: '80% ejecutado en eventos.',
    fundingSources: ['Regional Grants'],
    nextProposal: '10/01/2024',
    budgetProposalLink: '#',
    pastBudgets: [
      { title: 'Q1 2024 (Actual)', amount: '800 USD', link: '#' },
      { title: 'Q4 2023', amount: '600 USD', link: '#' }
    ],
    collaborations: [],
    toolsUsed: ['GitHub'],
    relatedProposals: [],
    ongoingDecisions: [],
    voteNowLink: '#',
    consensusArchiveLink: '#',
    participationMetrics: '10 Votes | 5 Comments | 80% Engagement',
    nextSteps: ['Actualizar portal'],
    milestoneTimelineLink: '#',
    openCalls: ['Buscamos voluntarios'],
    nextCycleProposalIdeas: ['Integrar API de visualización']
  },
  {
    name: 'Community Guild',
    type: 'Community',
    dateOfCreation: '05/05/2023',
    status: 'Active',
    anchorContacts: [
      { name: 'María López', role: 'Coordinator', handle: '@marial' }
    ],
    missionStatement: 'Fortalecer la comunidad y la participación.',
    goalsAndFocus: ['Engagement', 'Events'],
    totalMembers: '12 activos | 1 observador | 0 pendientes',
    roles: ['Organizers', 'Members'],
    memberDirectoryLink: '#',
    keyDeliverables: [
      { title: 'Community Meetup', status: 'In Progress', timeline: 'Q3 2024', description: 'Encuentro presencial de la comunidad.' }
    ],
    proposalSubmissions: [],
    frequency: 'Quarterly',
    meetingCalendarLink: '#',
    meetingNotesArchiveLink: '#',
    eventHostingParticipation: ['Meetup 2023', 'Foro Online'],
    createReportLink: '#',
    lastReportLink: '#',
    selfEvaluation: '🟢🟡',
    communityFeedback: 'Muy positivo',
    votingMetrics: '90% Participation / 95% Approval / 0 Abstention',
    currentBudgetTier: 'T2',
    currentBudget: '2000 USD',
    utilizationSummary: '80% ejecutado en eventos.',
    fundingSources: ['Regional Grants'],
    nextProposal: '10/01/2024',
    budgetProposalLink: '#',
    pastBudgets: [
      { title: 'Q2 2024 (Actual)', amount: '2000 USD', link: '#' },
      { title: 'Q1 2024', amount: '1800 USD', link: '#' }
    ],
    collaborations: [],
    toolsUsed: ['Notion', 'Discord'],
    relatedProposals: [],
    ongoingDecisions: [],
    voteNowLink: '#',
    consensusArchiveLink: '#',
    participationMetrics: '10 Votes | 5 Comments | 80% Engagement',
    nextSteps: ['Organizar próximo evento'],
    milestoneTimelineLink: '#',
    openCalls: ['Convocatoria para ponentes'],
    nextCycleProposalIdeas: ['Lanzar newsletter']
  },
  {
    name: 'Archives WG',
    type: 'Documentation',
    dateOfCreation: '04/01/2023',
    status: 'Inactive',
    anchorContacts: [{ name: 'Laura Smith', role: 'Archivist', handle: '@lauras' }],
    missionStatement: 'Gestionar archivos y documentación.',
    goalsAndFocus: ['Archivos', 'Documentación'],
    totalMembers: '3 activos | 0 observadores | 0 pendientes',
    roles: ['Archivistas'],
    memberDirectoryLink: '#',
    keyDeliverables: [{ title: 'Archivo Digital', status: 'Completed', timeline: 'Q2 2023', description: 'Digitalización de documentos.' }],
    proposalSubmissions: [],
    frequency: 'Quarterly',
    meetingCalendarLink: '#',
    meetingNotesArchiveLink: '#',
    eventHostingParticipation: ['Archivo Abierto'],
    createReportLink: '#',
    lastReportLink: '#',
    selfEvaluation: '🟢',
    communityFeedback: 'Positivo',
    votingMetrics: '70% Participation / 80% Approval / 0 Abstention',
    currentBudgetTier: 'T3',
    currentBudget: '500 USD',
    utilizationSummary: '60% ejecutado en digitalización.',
    fundingSources: ['Documentation Grants'],
    nextProposal: '12/01/2024',
    budgetProposalLink: '#',
    pastBudgets: [
      { title: 'Q2 2024 (Actual)', amount: '500 USD', link: '#' },
      { title: 'Q1 2024', amount: '400 USD', link: '#' }
    ],
    collaborations: [],
    toolsUsed: ['Notion'],
    relatedProposals: [],
    ongoingDecisions: [],
    voteNowLink: '#',
    consensusArchiveLink: '#',
    participationMetrics: '3 Votes | 1 Comment | 60% Engagement',
    nextSteps: ['Actualizar archivo'],
    milestoneTimelineLink: '#',
    openCalls: ['Convocatoria para digitalizadores'],
    nextCycleProposalIdeas: ['Crear archivo multimedia']
  },
  {
    name: 'Education Guild',
    type: 'Education',
    dateOfCreation: '06/01/2023',
    status: 'Active',
    anchorContacts: [{ name: 'Dr. Zhang', role: 'Coordinator', handle: '@zhang' }],
    missionStatement: 'Promover la educación y el aprendizaje en IA.',
    goalsAndFocus: ['Educación', 'Aprendizaje'],
    totalMembers: '15 activos | 2 observadores | 1 pendiente',
    roles: ['Educadores', 'Observadores'],
    memberDirectoryLink: '#',
    keyDeliverables: [{ title: 'Curso de IA', status: 'In Progress', timeline: 'Q4 2024', description: 'Curso en línea sobre IA.' }],
    proposalSubmissions: [],
    frequency: 'Monthly',
    meetingCalendarLink: '#',
    meetingNotesArchiveLink: '#',
    eventHostingParticipation: ['Webinar de IA para Educadores'],
    createReportLink: '#',
    lastReportLink: '#',
    selfEvaluation: '🟢🟡',
    communityFeedback: 'Muy positivo',
    votingMetrics: '95% Participation / 98% Approval / 0 Abstention',
    currentBudgetTier: 'T2',
    currentBudget: '2500 USD',
    utilizationSummary: '85% ejecutado en cursos.',
    fundingSources: ['Educational Grants'],
    nextProposal: '01/01/2025',
    budgetProposalLink: '#',
    pastBudgets: [
      { title: 'Q2 2024 (Actual)', amount: '2500 USD', link: '#' },
      { title: 'Q1 2024', amount: '2200 USD', link: '#' }
    ],
    collaborations: [],
    toolsUsed: ['Notion', 'Zoom'],
    relatedProposals: [],
    ongoingDecisions: [],
    voteNowLink: '#',
    consensusArchiveLink: '#',
    participationMetrics: '15 Votes | 10 Comments | 95% Engagement',
    nextSteps: ['Finalizar curso de IA'],
    milestoneTimelineLink: '#',
    openCalls: ['Convocatoria para ponentes'],
    nextCycleProposalIdeas: ['Crear programa de certificación']
  },
  {
    name: 'Gamers\' Guild',
    type: 'Community',
    dateOfCreation: '07/15/2023',
    status: 'Active',
    anchorContacts: [{ name: 'John Doe', role: 'Coordinator', handle: '@johndoe' }],
    missionStatement: 'Fortalecer la comunidad de jugadores y desarrolladores de IA.',
    goalsAndFocus: ['Juegos', 'Desarrollo'],
    totalMembers: '10 activos | 1 observador | 0 pendientes',
    roles: ['Jugadores', 'Desarrolladores'],
    memberDirectoryLink: '#',
    keyDeliverables: [{ title: 'Juego de IA', status: 'In Progress', timeline: 'Q3 2024', description: 'Juego interactivo para aprender IA.' }],
    proposalSubmissions: [],
    frequency: 'Weekly',
    meetingCalendarLink: '#',
    meetingNotesArchiveLink: '#',
    eventHostingParticipation: ['Juego de IA Demo'],
    createReportLink: '#',
    lastReportLink: '#',
    selfEvaluation: '🟢🟡',
    communityFeedback: 'Muy positivo',
    votingMetrics: '90% Participation / 95% Approval / 0 Abstention',
    currentBudgetTier: 'T2',
    currentBudget: '1800 USD',
    utilizationSummary: '85% ejecutado en juegos.',
    fundingSources: ['Community Grants'],
    nextProposal: '08/01/2024',
    budgetProposalLink: '#',
    pastBudgets: [
      { title: 'Q2 2024 (Actual)', amount: '1800 USD', link: '#' },
      { title: 'Q1 2024', amount: '1600 USD', link: '#' }
    ],
    collaborations: [],
    toolsUsed: ['Discord', 'GitHub'],
    relatedProposals: [],
    ongoingDecisions: [],
    voteNowLink: '#',
    consensusArchiveLink: '#',
    participationMetrics: '10 Votes | 5 Comments | 80% Engagement',
    nextSteps: ['Finalizar juego de IA'],
    milestoneTimelineLink: '#',
    openCalls: ['Convocatoria para desarrolladores'],
    nextCycleProposalIdeas: ['Lanzar evento de juegos']
  },
  {
    name: 'GitHub PBL WG',
    type: 'Project',
    dateOfCreation: '08/20/2023',
    status: 'Active',
    anchorContacts: [{ name: 'Alice Brown', role: 'Coordinator', handle: '@aliceb' }],
    missionStatement: 'Colaborar en proyectos de código abierto para IA.',
    goalsAndFocus: ['Código', 'Colaboración'],
    totalMembers: '15 activos | 3 observadores | 1 pendiente',
    roles: ['Colaboradores', 'Observadores'],
    memberDirectoryLink: '#',
    keyDeliverables: [{ title: 'Repositorio de IA', status: 'In Progress', timeline: 'Q4 2024', description: 'Repositorio de IA con proyectos.' }],
    proposalSubmissions: [],
    frequency: 'Daily',
    meetingCalendarLink: '#',
    meetingNotesArchiveLink: '#',
    eventHostingParticipation: ['Daily Standup'],
    createReportLink: '#',
    lastReportLink: '#',
    selfEvaluation: '🟢🟡',
    communityFeedback: 'Muy positivo',
    votingMetrics: '95% Participation / 98% Approval / 0 Abstention',
    currentBudgetTier: 'T2',
    currentBudget: '2000 USD',
    utilizationSummary: '90% ejecutado en código.',
    fundingSources: ['Community Grants'],
    nextProposal: '09/01/2024',
    budgetProposalLink: '#',
    pastBudgets: [
      { title: 'Q2 2024 (Actual)', amount: '2000 USD', link: '#' },
      { title: 'Q1 2024', amount: '1800 USD', link: '#' }
    ],
    collaborations: [],
    toolsUsed: ['GitHub', 'Notion'],
    relatedProposals: [],
    ongoingDecisions: [],
    voteNowLink: '#',
    consensusArchiveLink: '#',
    participationMetrics: '15 Votes | 10 Comments | 95% Engagement',
    nextSteps: ['Finalizar proyecto de IA'],
    milestoneTimelineLink: '#',
    openCalls: ['Convocatoria para colaboradores'],
    nextCycleProposalIdeas: ['Lanzar evento de código']
  },
  {
    name: 'Governance WG',
    type: 'Governance',
    dateOfCreation: '09/01/2023',
    status: 'Active',
    anchorContacts: [{ name: 'Bob White', role: 'Coordinator', handle: '@bobw' }],
    missionStatement: 'Gobernar y asegurar la dirección de la comunidad.',
    goalsAndFocus: ['Gobernanza', 'Dirección'],
    totalMembers: '12 activos | 4 observadores | 1 pendiente',
    roles: ['Gobernantes', 'Observadores'],
    memberDirectoryLink: '#',
    keyDeliverables: [{ title: 'Guía de Gobernanza', status: 'In Progress', timeline: 'Q3 2024', description: 'Guía de gobernanza para la comunidad.' }],
    proposalSubmissions: [],
    frequency: 'Weekly',
    meetingCalendarLink: '#',
    meetingNotesArchiveLink: '#',
    eventHostingParticipation: ['Webinar de Gobernanza'],
    createReportLink: '#',
    lastReportLink: '#',
    selfEvaluation: '🟢🟡',
    communityFeedback: 'Muy positivo',
    votingMetrics: '90% Participation / 95% Approval / 0 Abstention',
    currentBudgetTier: 'T2',
    currentBudget: '1800 USD',
    utilizationSummary: '85% ejecutado en gobernanza.',
    fundingSources: ['Community Grants'],
    nextProposal: '09/15/2024',
    budgetProposalLink: '#',
    pastBudgets: [
      { title: 'Q2 2024 (Actual)', amount: '1800 USD', link: '#' },
      { title: 'Q1 2024', amount: '1600 USD', link: '#' }
    ],
    collaborations: [],
    toolsUsed: ['Notion', 'Zoom'],
    relatedProposals: [],
    ongoingDecisions: [],
    voteNowLink: '#',
    consensusArchiveLink: '#',
    participationMetrics: '12 Votes | 8 Comments | 85% Engagement',
    nextSteps: ['Finalizar guía de gobernanza'],
    milestoneTimelineLink: '#',
    openCalls: ['Convocatoria para gobernantes'],
    nextCycleProposalIdeas: ['Lanzar evento de gobernanza']
  },
  {
    name: 'Knowledge Base WG',
    type: 'Documentation',
    dateOfCreation: '10/10/2023',
    status: 'Active',
    anchorContacts: [{ name: 'Charlie Black', role: 'Coordinator', handle: '@charlieb' }],
    missionStatement: 'Gestionar y mantener una base de conocimiento sobre IA.',
    goalsAndFocus: ['Conocimiento', 'Documentación'],
    totalMembers: '10 activos | 2 observadores | 0 pendientes',
    roles: ['Documentadores', 'Observadores'],
    memberDirectoryLink: '#',
    keyDeliverables: [{ title: 'Base de Conocimiento', status: 'In Progress', timeline: 'Q4 2024', description: 'Base de conocimiento sobre IA.' }],
    proposalSubmissions: [],
    frequency: 'Daily',
    meetingCalendarLink: '#',
    meetingNotesArchiveLink: '#',
    eventHostingParticipation: ['Daily Standup'],
    createReportLink: '#',
    lastReportLink: '#',
    selfEvaluation: '🟢🟡',
    communityFeedback: 'Muy positivo',
    votingMetrics: '95% Participation / 98% Approval / 0 Abstention',
    currentBudgetTier: 'T2',
    currentBudget: '1500 USD',
    utilizationSummary: '90% ejecutado en documentación.',
    fundingSources: ['Documentation Grants'],
    nextProposal: '10/15/2024',
    budgetProposalLink: '#',
    pastBudgets: [
      { title: 'Q2 2024 (Actual)', amount: '1500 USD', link: '#' },
      { title: 'Q1 2024', amount: '1300 USD', link: '#' }
    ],
    collaborations: [],
    toolsUsed: ['Notion', 'GitHub'],
    relatedProposals: [],
    ongoingDecisions: [],
    voteNowLink: '#',
    consensusArchiveLink: '#',
    participationMetrics: '10 Votes | 5 Comments | 80% Engagement',
    nextSteps: ['Finalizar base de conocimiento'],
    milestoneTimelineLink: '#',
    openCalls: ['Convocatoria para documentadores'],
    nextCycleProposalIdeas: ['Lanzar evento de documentación']
  },
  {
    name: 'LatAm Guild',
    type: 'Regional',
    dateOfCreation: '11/01/2023',
    status: 'Active',
    anchorContacts: [{ name: 'Maria Garcia', role: 'Coordinator', handle: '@mariag' }],
    missionStatement: 'Impulsar la colaboración y el desarrollo en América Latina.',
    goalsAndFocus: ['Inclusión', 'Desarrollo'],
    totalMembers: '15 activos | 3 observadores | 1 pendiente',
    roles: ['Core Contributors', 'Observers'],
    memberDirectoryLink: '#',
    keyDeliverables: [{ title: 'LatAm Summit', status: 'In Progress', timeline: 'Q3 2024', description: 'Evento anual de la guild.' }],
    proposalSubmissions: [],
    frequency: 'Monthly',
    meetingCalendarLink: '#',
    meetingNotesArchiveLink: '#',
    eventHostingParticipation: ['LatAm Summit 2023'],
    createReportLink: '#',
    lastReportLink: '#',
    selfEvaluation: '🟢🟡',
    communityFeedback: 'Muy positivo',
    votingMetrics: '90% Participation / 95% Approval / 0 Abstention',
    currentBudgetTier: 'T2',
    currentBudget: '2000 USD',
    utilizationSummary: '85% ejecutado en eventos.',
    fundingSources: ['Regional Grants'],
    nextProposal: '11/15/2024',
    budgetProposalLink: '#',
    pastBudgets: [
      { title: 'Q2 2024 (Actual)', amount: '2000 USD', link: '#' },
      { title: 'Q1 2024', amount: '1800 USD', link: '#' }
    ],
    collaborations: [],
    toolsUsed: ['Discord', 'Zoom'],
    relatedProposals: [],
    ongoingDecisions: [],
    voteNowLink: '#',
    consensusArchiveLink: '#',
    participationMetrics: '15 Votes | 10 Comments | 85% Engagement',
    nextSteps: ['Organizar próximo summit'],
    milestoneTimelineLink: '#',
    openCalls: ['Convocatoria para nuevos miembros'],
    nextCycleProposalIdeas: ['Expandir a nuevas regiones']
  },
  {
    name: 'Marketing Guild',
    type: 'Community',
    dateOfCreation: '12/01/2023',
    status: 'Active',
    anchorContacts: [{ name: 'David Lee', role: 'Coordinator', handle: '@davidl' }],
    missionStatement: 'Promover la comunidad y la visibilidad de la IA.',
    goalsAndFocus: ['Marketing', 'Visibilidad'],
    totalMembers: '10 activos | 2 observadores | 0 pendientes',
    roles: ['Marketing', 'Observadores'],
    memberDirectoryLink: '#',
    keyDeliverables: [{ title: 'Guía de Marketing', status: 'In Progress', timeline: 'Q3 2024', description: 'Guía de marketing para la comunidad.' }],
    proposalSubmissions: [],
    frequency: 'Weekly',
    meetingCalendarLink: '#',
    meetingNotesArchiveLink: '#',
    eventHostingParticipation: ['Webinar de Marketing'],
    createReportLink: '#',
    lastReportLink: '#',
    selfEvaluation: '🟢🟡',
    communityFeedback: 'Muy positivo',
    votingMetrics: '90% Participation / 95% Approval / 0 Abstention',
    currentBudgetTier: 'T2',
    currentBudget: '1500 USD',
    utilizationSummary: '85% ejecutado en marketing.',
    fundingSources: ['Community Grants'],
    nextProposal: '12/15/2024',
    budgetProposalLink: '#',
    pastBudgets: [
      { title: 'Q2 2024 (Actual)', amount: '1500 USD', link: '#' },
      { title: 'Q1 2024', amount: '1300 USD', link: '#' }
    ],
    collaborations: [],
    toolsUsed: ['Notion', 'Discord'],
    relatedProposals: [],
    ongoingDecisions: [],
    voteNowLink: '#',
    consensusArchiveLink: '#',
    participationMetrics: '10 Votes | 5 Comments | 80% Engagement',
    nextSteps: ['Finalizar guía de marketing'],
    milestoneTimelineLink: '#',
    openCalls: ['Convocatoria para marketing'],
    nextCycleProposalIdeas: ['Lanzar evento de marketing']
  },
  {
    name: 'Moderators WG',
    type: 'Community',
    dateOfCreation: '01/01/2024',
    status: 'Active',
    anchorContacts: [{ name: 'Eve Green', role: 'Coordinator', handle: '@eveg' }],
    missionStatement: 'Gobernar y moderar la comunidad.',
    goalsAndFocus: ['Gobernanza', 'Moderación'],
    totalMembers: '15 activos | 5 observadores | 0 pendientes',
    roles: ['Moderadores', 'Observadores'],
    memberDirectoryLink: '#',
    keyDeliverables: [{ title: 'Guía de Moderación', status: 'In Progress', timeline: 'Q3 2024', description: 'Guía de moderación para la comunidad.' }],
    proposalSubmissions: [],
    frequency: 'Daily',
    meetingCalendarLink: '#',
    meetingNotesArchiveLink: '#',
    eventHostingParticipation: ['Daily Standup'],
    createReportLink: '#',
    lastReportLink: '#',
    selfEvaluation: '🟢🟡',
    communityFeedback: 'Muy positivo',
    votingMetrics: '95% Participation / 98% Approval / 0 Abstention',
    currentBudgetTier: 'T2',
    currentBudget: '1800 USD',
    utilizationSummary: '90% ejecutado en moderación.',
    fundingSources: ['Community Grants'],
    nextProposal: '01/15/2025',
    budgetProposalLink: '#',
    pastBudgets: [
      { title: 'Q2 2024 (Actual)', amount: '1800 USD', link: '#' },
      { title: 'Q1 2024', amount: '1600 USD', link: '#' }
    ],
    collaborations: [],
    toolsUsed: ['Notion', 'Zoom'],
    relatedProposals: [],
    ongoingDecisions: [],
    voteNowLink: '#',
    consensusArchiveLink: '#',
    participationMetrics: '15 Votes | 10 Comments | 95% Engagement',
    nextSteps: ['Finalizar guía de moderación'],
    milestoneTimelineLink: '#',
    openCalls: ['Convocatoria para moderadores'],
    nextCycleProposalIdeas: ['Lanzar evento de moderación']
  },
  {
    name: 'Onboarding WG',
    type: 'Community',
    dateOfCreation: '02/01/2024',
    status: 'Active',
    anchorContacts: [{ name: 'Frank White', role: 'Coordinator', handle: '@frankw' }],
    missionStatement: 'Facilitar el proceso de incorporación de nuevos miembros.',
    goalsAndFocus: ['Incorporación', 'Facilitación'],
    totalMembers: '10 activos | 2 observadores | 0 pendientes',
    roles: ['Facilitadores', 'Observadores'],
    memberDirectoryLink: '#',
    keyDeliverables: [{ title: 'Guía de Onboarding', status: 'In Progress', timeline: 'Q3 2024', description: 'Guía de onboarding para nuevos miembros.' }],
    proposalSubmissions: [],
    frequency: 'Daily',
    meetingCalendarLink: '#',
    meetingNotesArchiveLink: '#',
    eventHostingParticipation: ['Daily Standup'],
    createReportLink: '#',
    lastReportLink: '#',
    selfEvaluation: '🟢🟡',
    communityFeedback: 'Muy positivo',
    votingMetrics: '95% Participation / 98% Approval / 0 Abstention',
    currentBudgetTier: 'T2',
    currentBudget: '1800 USD',
    utilizationSummary: '90% ejecutado en onboarding.',
    fundingSources: ['Community Grants'],
    nextProposal: '02/15/2025',
    budgetProposalLink: '#',
    pastBudgets: [
      { title: 'Q2 2024 (Actual)', amount: '1800 USD', link: '#' },
      { title: 'Q1 2024', amount: '1600 USD', link: '#' }
    ],
    collaborations: [],
    toolsUsed: ['Notion', 'Zoom'],
    relatedProposals: [],
    ongoingDecisions: [],
    voteNowLink: '#',
    consensusArchiveLink: '#',
    participationMetrics: '10 Votes | 5 Comments | 80% Engagement',
    nextSteps: ['Finalizar guía de onboarding'],
    milestoneTimelineLink: '#',
    openCalls: ['Convocatoria para facilitadores'],
    nextCycleProposalIdeas: ['Lanzar evento de onboarding']
  },
  {
    name: 'Process Guild',
    type: 'Community',
    dateOfCreation: '03/01/2024',
    status: 'Active',
    anchorContacts: [{ name: 'Grace Black', role: 'Coordinator', handle: '@graceb' }],
    missionStatement: 'Gobernar y mejorar los procesos de la comunidad.',
    goalsAndFocus: ['Gobernanza', 'Procesos'],
    totalMembers: '12 activos | 4 observadores | 0 pendientes',
    roles: ['Gobernantes', 'Observadores'],
    memberDirectoryLink: '#',
    keyDeliverables: [{ title: 'Guía de Procesos', status: 'In Progress', timeline: 'Q3 2024', description: 'Guía de procesos para la comunidad.' }],
    proposalSubmissions: [],
    frequency: 'Daily',
    meetingCalendarLink: '#',
    meetingNotesArchiveLink: '#',
    eventHostingParticipation: ['Daily Standup'],
    createReportLink: '#',
    lastReportLink: '#',
    selfEvaluation: '🟢🟡',
    communityFeedback: 'Muy positivo',
    votingMetrics: '95% Participation / 98% Approval / 0 Abstention',
    currentBudgetTier: 'T2',
    currentBudget: '1800 USD',
    utilizationSummary: '90% ejecutado en procesos.',
    fundingSources: ['Community Grants'],
    nextProposal: '03/15/2025',
    budgetProposalLink: '#',
    pastBudgets: [
      { title: 'Q2 2024 (Actual)', amount: '1800 USD', link: '#' },
      { title: 'Q1 2024', amount: '1600 USD', link: '#' }
    ],
    collaborations: [],
    toolsUsed: ['Notion', 'Zoom'],
    relatedProposals: [],
    ongoingDecisions: [],
    voteNowLink: '#',
    consensusArchiveLink: '#',
    participationMetrics: '12 Votes | 8 Comments | 85% Engagement',
    nextSteps: ['Finalizar guía de procesos'],
    milestoneTimelineLink: '#',
    openCalls: ['Convocatoria para gobernantes'],
    nextCycleProposalIdeas: ['Lanzar evento de procesos']
  },
  {
    name: 'R&D Guild',
    type: 'Research',
    dateOfCreation: '04/01/2024',
    status: 'Active',
    anchorContacts: [{ name: 'Hank White', role: 'Coordinator', handle: '@hankw' }],
    missionStatement: 'Promover la investigación y el desarrollo de IA.',
    goalsAndFocus: ['Investigación', 'Desarrollo'],
    totalMembers: '15 activos | 5 observadores | 0 pendientes',
    roles: ['Investigadores', 'Observadores'],
    memberDirectoryLink: '#',
    keyDeliverables: [{ title: 'Reporte de Investigación', status: 'In Progress', timeline: 'Q3 2024', description: 'Reporte de investigación sobre IA.' }],
    proposalSubmissions: [],
    frequency: 'Weekly',
    meetingCalendarLink: '#',
    meetingNotesArchiveLink: '#',
    eventHostingParticipation: ['Webinar de Investigación'],
    createReportLink: '#',
    lastReportLink: '#',
    selfEvaluation: '🟢🟡',
    communityFeedback: 'Muy positivo',
    votingMetrics: '90% Participation / 95% Approval / 0 Abstention',
    currentBudgetTier: 'T2',
    currentBudget: '1800 USD',
    utilizationSummary: '85% ejecutado en investigación.',
    fundingSources: ['Research Grants'],
    nextProposal: '04/15/2025',
    budgetProposalLink: '#',
    pastBudgets: [
      { title: 'Q2 2024 (Actual)', amount: '1800 USD', link: '#' },
      { title: 'Q1 2024', amount: '1600 USD', link: '#' }
    ],
    collaborations: [],
    toolsUsed: ['Notion', 'Zoom'],
    relatedProposals: [],
    ongoingDecisions: [],
    voteNowLink: '#',
    consensusArchiveLink: '#',
    participationMetrics: '15 Votes | 10 Comments | 85% Engagement',
    nextSteps: ['Finalizar reporte de investigación'],
    milestoneTimelineLink: '#',
    openCalls: ['Convocatoria para investigadores'],
    nextCycleProposalIdeas: ['Lanzar evento de investigación']
  },
  {
    name: 'Strategy Guild',
    type: 'Governance',
    dateOfCreation: '05/01/2024',
    status: 'Active',
    anchorContacts: [{ name: 'Ivy Green', role: 'Coordinator', handle: '@ivyg' }],
    missionStatement: 'Gobernar y definir la estrategia de la comunidad.',
    goalsAndFocus: ['Gobernanza', 'Estrategia'],
    totalMembers: '10 activos | 3 observadores | 0 pendientes',
    roles: ['Gobernantes', 'Observadores'],
    memberDirectoryLink: '#',
    keyDeliverables: [{ title: 'Guía de Estrategia', status: 'In Progress', timeline: 'Q3 2024', description: 'Guía de estrategia para la comunidad.' }],
    proposalSubmissions: [],
    frequency: 'Daily',
    meetingCalendarLink: '#',
    meetingNotesArchiveLink: '#',
    eventHostingParticipation: ['Daily Standup'],
    createReportLink: '#',
    lastReportLink: '#',
    selfEvaluation: '🟢🟡',
    communityFeedback: 'Muy positivo',
    votingMetrics: '95% Participation / 98% Approval / 0 Abstention',
    currentBudgetTier: 'T2',
    currentBudget: '1800 USD',
    utilizationSummary: '90% ejecutado en estrategia.',
    fundingSources: ['Community Grants'],
    nextProposal: '05/15/2025',
    budgetProposalLink: '#',
    pastBudgets: [
      { title: 'Q2 2024 (Actual)', amount: '1800 USD', link: '#' },
      { title: 'Q1 2024', amount: '1600 USD', link: '#' }
    ],
    collaborations: [],
    toolsUsed: ['Notion', 'Zoom'],
    relatedProposals: [],
    ongoingDecisions: [],
    voteNowLink: '#',
    consensusArchiveLink: '#',
    participationMetrics: '10 Votes | 5 Comments | 80% Engagement',
    nextSteps: ['Finalizar guía de estrategia'],
    milestoneTimelineLink: '#',
    openCalls: ['Convocatoria para gobernantes'],
    nextCycleProposalIdeas: ['Lanzar evento de estrategia']
  },
  {
    name: 'Translators WG',
    type: 'Community',
    dateOfCreation: '06/01/2024',
    status: 'Active',
    anchorContacts: [{ name: 'Jack Black', role: 'Coordinator', handle: '@jackb' }],
    missionStatement: 'Traducir contenido y documentación de la comunidad.',
    goalsAndFocus: ['Traducción', 'Documentación'],
    totalMembers: '12 activos | 4 observadores | 0 pendientes',
    roles: ['Traductores', 'Observadores'],
    memberDirectoryLink: '#',
    keyDeliverables: [{ title: 'Guía de Traducción', status: 'In Progress', timeline: 'Q3 2024', description: 'Guía de traducción para la comunidad.' }],
    proposalSubmissions: [],
    frequency: 'Daily',
    meetingCalendarLink: '#',
    meetingNotesArchiveLink: '#',
    eventHostingParticipation: ['Daily Standup'],
    createReportLink: '#',
    lastReportLink: '#',
    selfEvaluation: '🟢🟡',
    communityFeedback: 'Muy positivo',
    votingMetrics: '95% Participation / 98% Approval / 0 Abstention',
    currentBudgetTier: 'T2',
    currentBudget: '1800 USD',
    utilizationSummary: '90% ejecutado en traducción.',
    fundingSources: ['Community Grants'],
    nextProposal: '06/15/2025',
    budgetProposalLink: '#',
    pastBudgets: [
      { title: 'Q2 2024 (Actual)', amount: '1800 USD', link: '#' },
      { title: 'Q1 2024', amount: '1600 USD', link: '#' }
    ],
    collaborations: [],
    toolsUsed: ['Notion', 'Zoom'],
    relatedProposals: [],
    ongoingDecisions: [],
    voteNowLink: '#',
    consensusArchiveLink: '#',
    participationMetrics: '12 Votes | 8 Comments | 85% Engagement',
    nextSteps: ['Finalizar guía de traducción'],
    milestoneTimelineLink: '#',
    openCalls: ['Convocatoria para traductores'],
    nextCycleProposalIdeas: ['Lanzar evento de traducción']
  },
  {
    name: 'Treasury Automation WG',
    type: 'Community',
    dateOfCreation: '07/01/2024',
    status: 'Active',
    anchorContacts: [{ name: 'Kyle Green', role: 'Coordinator', handle: '@kyleg' }],
    missionStatement: 'Automatizar y mejorar el proceso de gestión de recursos.',
    goalsAndFocus: ['Automatización', 'Recursos'],
    totalMembers: '10 activos | 3 observadores | 0 pendientes',
    roles: ['Automatizadores', 'Observadores'],
    memberDirectoryLink: '#',
    keyDeliverables: [{ title: 'Guía de Recursos', status: 'In Progress', timeline: 'Q3 2024', description: 'Guía de recursos para la comunidad.' }],
    proposalSubmissions: [],
    frequency: 'Daily',
    meetingCalendarLink: '#',
    meetingNotesArchiveLink: '#',
    eventHostingParticipation: ['Daily Standup'],
    createReportLink: '#',
    lastReportLink: '#',
    selfEvaluation: '🟢🟡',
    communityFeedback: 'Muy positivo',
    votingMetrics: '95% Participation / 98% Approval / 0 Abstention',
    currentBudgetTier: 'T2',
    currentBudget: '1800 USD',
    utilizationSummary: '90% ejecutado en recursos.',
    fundingSources: ['Community Grants'],
    nextProposal: '07/15/2025',
    budgetProposalLink: '#',
    pastBudgets: [
      { title: 'Q2 2024 (Actual)', amount: '1800 USD', link: '#' },
      { title: 'Q1 2024', amount: '1600 USD', link: '#' }
    ],
    collaborations: [],
    toolsUsed: ['Notion', 'Zoom'],
    relatedProposals: [],
    ongoingDecisions: [],
    voteNowLink: '#',
    consensusArchiveLink: '#',
    participationMetrics: '10 Votes | 5 Comments | 80% Engagement',
    nextSteps: ['Finalizar guía de recursos'],
    milestoneTimelineLink: '#',
    openCalls: ['Convocatoria para automatizadores'],
    nextCycleProposalIdeas: ['Lanzar evento de recursos']
  },
  {
    name: 'Treasury Guild',
    type: 'Community',
    dateOfCreation: '08/01/2024',
    status: 'Active',
    anchorContacts: [{ name: 'Liam Black', role: 'Coordinator', handle: '@liamb' }],
    missionStatement: 'Gobernar y gestionar los recursos financieros de la comunidad.',
    goalsAndFocus: ['Recursos', 'Financiación'],
    totalMembers: '12 activos | 4 observadores | 0 pendientes',
    roles: ['Gobernantes', 'Observadores'],
    memberDirectoryLink: '#',
    keyDeliverables: [{ title: 'Guía de Financiación', status: 'In Progress', timeline: 'Q3 2024', description: 'Guía de financiación para la comunidad.' }],
    proposalSubmissions: [],
    frequency: 'Daily',
    meetingCalendarLink: '#',
    meetingNotesArchiveLink: '#',
    eventHostingParticipation: ['Daily Standup'],
    createReportLink: '#',
    lastReportLink: '#',
    selfEvaluation: '🟢🟡',
    communityFeedback: 'Muy positivo',
    votingMetrics: '95% Participation / 98% Approval / 0 Abstention',
    currentBudgetTier: 'T2',
    currentBudget: '1800 USD',
    utilizationSummary: '90% ejecutado en financiación.',
    fundingSources: ['Community Grants'],
    nextProposal: '08/15/2025',
    budgetProposalLink: '#',
    pastBudgets: [
      { title: 'Q2 2024 (Actual)', amount: '1800 USD', link: '#' },
      { title: 'Q1 2024', amount: '1600 USD', link: '#' }
    ],
    collaborations: [],
    toolsUsed: ['Notion', 'Zoom'],
    relatedProposals: [],
    ongoingDecisions: [],
    voteNowLink: '#',
    consensusArchiveLink: '#',
    participationMetrics: '12 Votes | 8 Comments | 85% Engagement',
    nextSteps: ['Finalizar guía de financiación'],
    milestoneTimelineLink: '#',
    openCalls: ['Convocatoria para gobernantes'],
    nextCycleProposalIdeas: ['Lanzar evento de financiación']
  },
  {
    name: 'Video WG',
    type: 'Community',
    dateOfCreation: '09/01/2024',
    status: 'Active',
    anchorContacts: [{ name: 'Mia Green', role: 'Coordinator', handle: '@miag' }],
    missionStatement: 'Gobernar y gestionar el contenido de video de la comunidad.',
    goalsAndFocus: ['Video', 'Gobernanza'],
    totalMembers: '10 activos | 3 observadores | 0 pendientes',
    roles: ['Gobernantes', 'Observadores'],
    memberDirectoryLink: '#',
    keyDeliverables: [{ title: 'Guía de Video', status: 'In Progress', timeline: 'Q3 2024', description: 'Guía de video para la comunidad.' }],
    proposalSubmissions: [],
    frequency: 'Daily',
    meetingCalendarLink: '#',
    meetingNotesArchiveLink: '#',
    eventHostingParticipation: ['Daily Standup'],
    createReportLink: '#',
    lastReportLink: '#',
    selfEvaluation: '🟢🟡',
    communityFeedback: 'Muy positivo',
    votingMetrics: '95% Participation / 98% Approval / 0 Abstention',
    currentBudgetTier: 'T2',
    currentBudget: '1800 USD',
    utilizationSummary: '90% ejecutado en video.',
    fundingSources: ['Community Grants'],
    nextProposal: '09/15/2025',
    budgetProposalLink: '#',
    pastBudgets: [
      { title: 'Q2 2024 (Actual)', amount: '1800 USD', link: '#' },
      { title: 'Q1 2024', amount: '1600 USD', link: '#' }
    ],
    collaborations: [],
    toolsUsed: ['Notion', 'Zoom'],
    relatedProposals: [],
    ongoingDecisions: [],
    voteNowLink: '#',
    consensusArchiveLink: '#',
    participationMetrics: '10 Votes | 5 Comments | 80% Engagement',
    nextSteps: ['Finalizar guía de video'],
    milestoneTimelineLink: '#',
    openCalls: ['Convocatoria para gobernantes'],
    nextCycleProposalIdeas: ['Lanzar evento de video']
  },
  {
    name: 'Writers WG',
    type: 'Community',
    dateOfCreation: '10/01/2024',
    status: 'Active',
    anchorContacts: [{ name: 'Noah Black', role: 'Coordinator', handle: '@noahb' }],
    missionStatement: 'Gobernar y gestionar el contenido escrito de la comunidad.',
    goalsAndFocus: ['Escritura', 'Gobernanza'],
    totalMembers: '12 activos | 4 observadores | 0 pendientes',
    roles: ['Gobernantes', 'Observadores'],
    memberDirectoryLink: '#',
    keyDeliverables: [{ title: 'Guía de Escritura', status: 'In Progress', timeline: 'Q3 2024', description: 'Guía de escritura para la comunidad.' }],
    proposalSubmissions: [],
    frequency: 'Daily',
    meetingCalendarLink: '#',
    meetingNotesArchiveLink: '#',
    eventHostingParticipation: ['Daily Standup'],
    createReportLink: '#',
    lastReportLink: '#',
    selfEvaluation: '🟢🟡',
    communityFeedback: 'Muy positivo',
    votingMetrics: '95% Participation / 98% Approval / 0 Abstention',
    currentBudgetTier: 'T2',
    currentBudget: '1800 USD',
    utilizationSummary: '90% ejecutado en escritura.',
    fundingSources: ['Community Grants'],
    nextProposal: '10/15/2025',
    budgetProposalLink: '#',
    pastBudgets: [
      { title: 'Q2 2024 (Actual)', amount: '1800 USD', link: '#' },
      { title: 'Q1 2024', amount: '1600 USD', link: '#' }
    ],
    collaborations: [],
    toolsUsed: ['Notion', 'Zoom'],
    relatedProposals: [],
    ongoingDecisions: [],
    voteNowLink: '#',
    consensusArchiveLink: '#',
    participationMetrics: '12 Votes | 8 Comments | 85% Engagement',
    nextSteps: ['Finalizar guía de escritura'],
    milestoneTimelineLink: '#',
    openCalls: ['Convocatoria para gobernantes'],
    nextCycleProposalIdeas: ['Lanzar evento de escritura']
  }
]; 